// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

// Protobuf Java Version: 3.25.1
package ru.ccfit.golubevm.snake.protobuf.protocol;

/**
 * Protobuf type {@code snakes.GameAnnouncement}
 */
public final class GameAnnouncement extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:snakes.GameAnnouncement)
    GameAnnouncementOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GameAnnouncement.newBuilder() to construct.
  private GameAnnouncement(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GameAnnouncement() {
    canJoin_ = true;
    gameName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GameAnnouncement();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.ccfit.golubevm.snake.protobuf.protocol.SnakesProto.internal_static_snakes_GameAnnouncement_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.ccfit.golubevm.snake.protobuf.protocol.SnakesProto.internal_static_snakes_GameAnnouncement_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement.class, ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement.Builder.class);
  }

  private int bitField0_;
  public static final int PLAYERS_FIELD_NUMBER = 1;
  private ru.ccfit.golubevm.snake.protobuf.protocol.GamePlayers players_;
  /**
   * <pre>
   * Текущие игроки
   * </pre>
   *
   * <code>required .snakes.GamePlayers players = 1;</code>
   * @return Whether the players field is set.
   */
  @java.lang.Override
  public boolean hasPlayers() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Текущие игроки
   * </pre>
   *
   * <code>required .snakes.GamePlayers players = 1;</code>
   * @return The players.
   */
  @java.lang.Override
  public ru.ccfit.golubevm.snake.protobuf.protocol.GamePlayers getPlayers() {
    return players_ == null ? ru.ccfit.golubevm.snake.protobuf.protocol.GamePlayers.getDefaultInstance() : players_;
  }
  /**
   * <pre>
   * Текущие игроки
   * </pre>
   *
   * <code>required .snakes.GamePlayers players = 1;</code>
   */
  @java.lang.Override
  public ru.ccfit.golubevm.snake.protobuf.protocol.GamePlayersOrBuilder getPlayersOrBuilder() {
    return players_ == null ? ru.ccfit.golubevm.snake.protobuf.protocol.GamePlayers.getDefaultInstance() : players_;
  }

  public static final int CONFIG_FIELD_NUMBER = 2;
  private ru.ccfit.golubevm.snake.protobuf.protocol.GameConfig config_;
  /**
   * <pre>
   * Параметры игры
   * </pre>
   *
   * <code>required .snakes.GameConfig config = 2;</code>
   * @return Whether the config field is set.
   */
  @java.lang.Override
  public boolean hasConfig() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Параметры игры
   * </pre>
   *
   * <code>required .snakes.GameConfig config = 2;</code>
   * @return The config.
   */
  @java.lang.Override
  public ru.ccfit.golubevm.snake.protobuf.protocol.GameConfig getConfig() {
    return config_ == null ? ru.ccfit.golubevm.snake.protobuf.protocol.GameConfig.getDefaultInstance() : config_;
  }
  /**
   * <pre>
   * Параметры игры
   * </pre>
   *
   * <code>required .snakes.GameConfig config = 2;</code>
   */
  @java.lang.Override
  public ru.ccfit.golubevm.snake.protobuf.protocol.GameConfigOrBuilder getConfigOrBuilder() {
    return config_ == null ? ru.ccfit.golubevm.snake.protobuf.protocol.GameConfig.getDefaultInstance() : config_;
  }

  public static final int CAN_JOIN_FIELD_NUMBER = 3;
  private boolean canJoin_ = true;
  /**
   * <pre>
   * Можно ли новому игроку присоединиться к игре (есть ли место на поле)
   * </pre>
   *
   * <code>optional bool can_join = 3 [default = true];</code>
   * @return Whether the canJoin field is set.
   */
  @java.lang.Override
  public boolean hasCanJoin() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * Можно ли новому игроку присоединиться к игре (есть ли место на поле)
   * </pre>
   *
   * <code>optional bool can_join = 3 [default = true];</code>
   * @return The canJoin.
   */
  @java.lang.Override
  public boolean getCanJoin() {
    return canJoin_;
  }

  public static final int GAME_NAME_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object gameName_ = "";
  /**
   * <pre>
   * Глобально уникальное имя игры, например "my game"
   * </pre>
   *
   * <code>required string game_name = 4;</code>
   * @return Whether the gameName field is set.
   */
  @java.lang.Override
  public boolean hasGameName() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   * Глобально уникальное имя игры, например "my game"
   * </pre>
   *
   * <code>required string game_name = 4;</code>
   * @return The gameName.
   */
  @java.lang.Override
  public java.lang.String getGameName() {
    java.lang.Object ref = gameName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        gameName_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * Глобально уникальное имя игры, например "my game"
   * </pre>
   *
   * <code>required string game_name = 4;</code>
   * @return The bytes for gameName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGameNameBytes() {
    java.lang.Object ref = gameName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gameName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasPlayers()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasConfig()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasGameName()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getPlayers().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getPlayers());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getConfig());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeBool(3, canJoin_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, gameName_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPlayers());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getConfig());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, canJoin_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, gameName_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement)) {
      return super.equals(obj);
    }
    ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement other = (ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement) obj;

    if (hasPlayers() != other.hasPlayers()) return false;
    if (hasPlayers()) {
      if (!getPlayers()
          .equals(other.getPlayers())) return false;
    }
    if (hasConfig() != other.hasConfig()) return false;
    if (hasConfig()) {
      if (!getConfig()
          .equals(other.getConfig())) return false;
    }
    if (hasCanJoin() != other.hasCanJoin()) return false;
    if (hasCanJoin()) {
      if (getCanJoin()
          != other.getCanJoin()) return false;
    }
    if (hasGameName() != other.hasGameName()) return false;
    if (hasGameName()) {
      if (!getGameName()
          .equals(other.getGameName())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPlayers()) {
      hash = (37 * hash) + PLAYERS_FIELD_NUMBER;
      hash = (53 * hash) + getPlayers().hashCode();
    }
    if (hasConfig()) {
      hash = (37 * hash) + CONFIG_FIELD_NUMBER;
      hash = (53 * hash) + getConfig().hashCode();
    }
    if (hasCanJoin()) {
      hash = (37 * hash) + CAN_JOIN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getCanJoin());
    }
    if (hasGameName()) {
      hash = (37 * hash) + GAME_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getGameName().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code snakes.GameAnnouncement}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:snakes.GameAnnouncement)
      ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncementOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.ccfit.golubevm.snake.protobuf.protocol.SnakesProto.internal_static_snakes_GameAnnouncement_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.ccfit.golubevm.snake.protobuf.protocol.SnakesProto.internal_static_snakes_GameAnnouncement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement.class, ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement.Builder.class);
    }

    // Construct using ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPlayersFieldBuilder();
        getConfigFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      players_ = null;
      if (playersBuilder_ != null) {
        playersBuilder_.dispose();
        playersBuilder_ = null;
      }
      config_ = null;
      if (configBuilder_ != null) {
        configBuilder_.dispose();
        configBuilder_ = null;
      }
      canJoin_ = true;
      gameName_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.ccfit.golubevm.snake.protobuf.protocol.SnakesProto.internal_static_snakes_GameAnnouncement_descriptor;
    }

    @java.lang.Override
    public ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement getDefaultInstanceForType() {
      return ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement.getDefaultInstance();
    }

    @java.lang.Override
    public ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement build() {
      ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement buildPartial() {
      ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement result = new ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.players_ = playersBuilder_ == null
            ? players_
            : playersBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.config_ = configBuilder_ == null
            ? config_
            : configBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.canJoin_ = canJoin_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.gameName_ = gameName_;
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement) {
        return mergeFrom((ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement other) {
      if (other == ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement.getDefaultInstance()) return this;
      if (other.hasPlayers()) {
        mergePlayers(other.getPlayers());
      }
      if (other.hasConfig()) {
        mergeConfig(other.getConfig());
      }
      if (other.hasCanJoin()) {
        setCanJoin(other.getCanJoin());
      }
      if (other.hasGameName()) {
        gameName_ = other.gameName_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasPlayers()) {
        return false;
      }
      if (!hasConfig()) {
        return false;
      }
      if (!hasGameName()) {
        return false;
      }
      if (!getPlayers().isInitialized()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getPlayersFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getConfigFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              canJoin_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              gameName_ = input.readBytes();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private ru.ccfit.golubevm.snake.protobuf.protocol.GamePlayers players_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.ccfit.golubevm.snake.protobuf.protocol.GamePlayers, ru.ccfit.golubevm.snake.protobuf.protocol.GamePlayers.Builder, ru.ccfit.golubevm.snake.protobuf.protocol.GamePlayersOrBuilder> playersBuilder_;
    /**
     * <pre>
     * Текущие игроки
     * </pre>
     *
     * <code>required .snakes.GamePlayers players = 1;</code>
     * @return Whether the players field is set.
     */
    public boolean hasPlayers() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Текущие игроки
     * </pre>
     *
     * <code>required .snakes.GamePlayers players = 1;</code>
     * @return The players.
     */
    public ru.ccfit.golubevm.snake.protobuf.protocol.GamePlayers getPlayers() {
      if (playersBuilder_ == null) {
        return players_ == null ? ru.ccfit.golubevm.snake.protobuf.protocol.GamePlayers.getDefaultInstance() : players_;
      } else {
        return playersBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Текущие игроки
     * </pre>
     *
     * <code>required .snakes.GamePlayers players = 1;</code>
     */
    public Builder setPlayers(ru.ccfit.golubevm.snake.protobuf.protocol.GamePlayers value) {
      if (playersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        players_ = value;
      } else {
        playersBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Текущие игроки
     * </pre>
     *
     * <code>required .snakes.GamePlayers players = 1;</code>
     */
    public Builder setPlayers(
        ru.ccfit.golubevm.snake.protobuf.protocol.GamePlayers.Builder builderForValue) {
      if (playersBuilder_ == null) {
        players_ = builderForValue.build();
      } else {
        playersBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Текущие игроки
     * </pre>
     *
     * <code>required .snakes.GamePlayers players = 1;</code>
     */
    public Builder mergePlayers(ru.ccfit.golubevm.snake.protobuf.protocol.GamePlayers value) {
      if (playersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          players_ != null &&
          players_ != ru.ccfit.golubevm.snake.protobuf.protocol.GamePlayers.getDefaultInstance()) {
          getPlayersBuilder().mergeFrom(value);
        } else {
          players_ = value;
        }
      } else {
        playersBuilder_.mergeFrom(value);
      }
      if (players_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Текущие игроки
     * </pre>
     *
     * <code>required .snakes.GamePlayers players = 1;</code>
     */
    public Builder clearPlayers() {
      bitField0_ = (bitField0_ & ~0x00000001);
      players_ = null;
      if (playersBuilder_ != null) {
        playersBuilder_.dispose();
        playersBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Текущие игроки
     * </pre>
     *
     * <code>required .snakes.GamePlayers players = 1;</code>
     */
    public ru.ccfit.golubevm.snake.protobuf.protocol.GamePlayers.Builder getPlayersBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getPlayersFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Текущие игроки
     * </pre>
     *
     * <code>required .snakes.GamePlayers players = 1;</code>
     */
    public ru.ccfit.golubevm.snake.protobuf.protocol.GamePlayersOrBuilder getPlayersOrBuilder() {
      if (playersBuilder_ != null) {
        return playersBuilder_.getMessageOrBuilder();
      } else {
        return players_ == null ?
            ru.ccfit.golubevm.snake.protobuf.protocol.GamePlayers.getDefaultInstance() : players_;
      }
    }
    /**
     * <pre>
     * Текущие игроки
     * </pre>
     *
     * <code>required .snakes.GamePlayers players = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.ccfit.golubevm.snake.protobuf.protocol.GamePlayers, ru.ccfit.golubevm.snake.protobuf.protocol.GamePlayers.Builder, ru.ccfit.golubevm.snake.protobuf.protocol.GamePlayersOrBuilder> 
        getPlayersFieldBuilder() {
      if (playersBuilder_ == null) {
        playersBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.ccfit.golubevm.snake.protobuf.protocol.GamePlayers, ru.ccfit.golubevm.snake.protobuf.protocol.GamePlayers.Builder, ru.ccfit.golubevm.snake.protobuf.protocol.GamePlayersOrBuilder>(
                getPlayers(),
                getParentForChildren(),
                isClean());
        players_ = null;
      }
      return playersBuilder_;
    }

    private ru.ccfit.golubevm.snake.protobuf.protocol.GameConfig config_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.ccfit.golubevm.snake.protobuf.protocol.GameConfig, ru.ccfit.golubevm.snake.protobuf.protocol.GameConfig.Builder, ru.ccfit.golubevm.snake.protobuf.protocol.GameConfigOrBuilder> configBuilder_;
    /**
     * <pre>
     * Параметры игры
     * </pre>
     *
     * <code>required .snakes.GameConfig config = 2;</code>
     * @return Whether the config field is set.
     */
    public boolean hasConfig() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Параметры игры
     * </pre>
     *
     * <code>required .snakes.GameConfig config = 2;</code>
     * @return The config.
     */
    public ru.ccfit.golubevm.snake.protobuf.protocol.GameConfig getConfig() {
      if (configBuilder_ == null) {
        return config_ == null ? ru.ccfit.golubevm.snake.protobuf.protocol.GameConfig.getDefaultInstance() : config_;
      } else {
        return configBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Параметры игры
     * </pre>
     *
     * <code>required .snakes.GameConfig config = 2;</code>
     */
    public Builder setConfig(ru.ccfit.golubevm.snake.protobuf.protocol.GameConfig value) {
      if (configBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        config_ = value;
      } else {
        configBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Параметры игры
     * </pre>
     *
     * <code>required .snakes.GameConfig config = 2;</code>
     */
    public Builder setConfig(
        ru.ccfit.golubevm.snake.protobuf.protocol.GameConfig.Builder builderForValue) {
      if (configBuilder_ == null) {
        config_ = builderForValue.build();
      } else {
        configBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Параметры игры
     * </pre>
     *
     * <code>required .snakes.GameConfig config = 2;</code>
     */
    public Builder mergeConfig(ru.ccfit.golubevm.snake.protobuf.protocol.GameConfig value) {
      if (configBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          config_ != null &&
          config_ != ru.ccfit.golubevm.snake.protobuf.protocol.GameConfig.getDefaultInstance()) {
          getConfigBuilder().mergeFrom(value);
        } else {
          config_ = value;
        }
      } else {
        configBuilder_.mergeFrom(value);
      }
      if (config_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Параметры игры
     * </pre>
     *
     * <code>required .snakes.GameConfig config = 2;</code>
     */
    public Builder clearConfig() {
      bitField0_ = (bitField0_ & ~0x00000002);
      config_ = null;
      if (configBuilder_ != null) {
        configBuilder_.dispose();
        configBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Параметры игры
     * </pre>
     *
     * <code>required .snakes.GameConfig config = 2;</code>
     */
    public ru.ccfit.golubevm.snake.protobuf.protocol.GameConfig.Builder getConfigBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getConfigFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Параметры игры
     * </pre>
     *
     * <code>required .snakes.GameConfig config = 2;</code>
     */
    public ru.ccfit.golubevm.snake.protobuf.protocol.GameConfigOrBuilder getConfigOrBuilder() {
      if (configBuilder_ != null) {
        return configBuilder_.getMessageOrBuilder();
      } else {
        return config_ == null ?
            ru.ccfit.golubevm.snake.protobuf.protocol.GameConfig.getDefaultInstance() : config_;
      }
    }
    /**
     * <pre>
     * Параметры игры
     * </pre>
     *
     * <code>required .snakes.GameConfig config = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ru.ccfit.golubevm.snake.protobuf.protocol.GameConfig, ru.ccfit.golubevm.snake.protobuf.protocol.GameConfig.Builder, ru.ccfit.golubevm.snake.protobuf.protocol.GameConfigOrBuilder> 
        getConfigFieldBuilder() {
      if (configBuilder_ == null) {
        configBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ru.ccfit.golubevm.snake.protobuf.protocol.GameConfig, ru.ccfit.golubevm.snake.protobuf.protocol.GameConfig.Builder, ru.ccfit.golubevm.snake.protobuf.protocol.GameConfigOrBuilder>(
                getConfig(),
                getParentForChildren(),
                isClean());
        config_ = null;
      }
      return configBuilder_;
    }

    private boolean canJoin_ = true;
    /**
     * <pre>
     * Можно ли новому игроку присоединиться к игре (есть ли место на поле)
     * </pre>
     *
     * <code>optional bool can_join = 3 [default = true];</code>
     * @return Whether the canJoin field is set.
     */
    @java.lang.Override
    public boolean hasCanJoin() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Можно ли новому игроку присоединиться к игре (есть ли место на поле)
     * </pre>
     *
     * <code>optional bool can_join = 3 [default = true];</code>
     * @return The canJoin.
     */
    @java.lang.Override
    public boolean getCanJoin() {
      return canJoin_;
    }
    /**
     * <pre>
     * Можно ли новому игроку присоединиться к игре (есть ли место на поле)
     * </pre>
     *
     * <code>optional bool can_join = 3 [default = true];</code>
     * @param value The canJoin to set.
     * @return This builder for chaining.
     */
    public Builder setCanJoin(boolean value) {

      canJoin_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Можно ли новому игроку присоединиться к игре (есть ли место на поле)
     * </pre>
     *
     * <code>optional bool can_join = 3 [default = true];</code>
     * @return This builder for chaining.
     */
    public Builder clearCanJoin() {
      bitField0_ = (bitField0_ & ~0x00000004);
      canJoin_ = true;
      onChanged();
      return this;
    }

    private java.lang.Object gameName_ = "";
    /**
     * <pre>
     * Глобально уникальное имя игры, например "my game"
     * </pre>
     *
     * <code>required string game_name = 4;</code>
     * @return Whether the gameName field is set.
     */
    public boolean hasGameName() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Глобально уникальное имя игры, например "my game"
     * </pre>
     *
     * <code>required string game_name = 4;</code>
     * @return The gameName.
     */
    public java.lang.String getGameName() {
      java.lang.Object ref = gameName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          gameName_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Глобально уникальное имя игры, например "my game"
     * </pre>
     *
     * <code>required string game_name = 4;</code>
     * @return The bytes for gameName.
     */
    public com.google.protobuf.ByteString
        getGameNameBytes() {
      java.lang.Object ref = gameName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gameName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Глобально уникальное имя игры, например "my game"
     * </pre>
     *
     * <code>required string game_name = 4;</code>
     * @param value The gameName to set.
     * @return This builder for chaining.
     */
    public Builder setGameName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      gameName_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Глобально уникальное имя игры, например "my game"
     * </pre>
     *
     * <code>required string game_name = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearGameName() {
      gameName_ = getDefaultInstance().getGameName();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Глобально уникальное имя игры, например "my game"
     * </pre>
     *
     * <code>required string game_name = 4;</code>
     * @param value The bytes for gameName to set.
     * @return This builder for chaining.
     */
    public Builder setGameNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      gameName_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:snakes.GameAnnouncement)
  }

  // @@protoc_insertion_point(class_scope:snakes.GameAnnouncement)
  private static final ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement();
  }

  public static ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<GameAnnouncement>
      PARSER = new com.google.protobuf.AbstractParser<GameAnnouncement>() {
    @java.lang.Override
    public GameAnnouncement parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GameAnnouncement> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GameAnnouncement> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.ccfit.golubevm.snake.protobuf.protocol.GameAnnouncement getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

