// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

// Protobuf Java Version: 3.25.1
package ru.ccfit.golubevm.snake.protobuf.protocol;

public interface GameAnnouncementOrBuilder extends
    // @@protoc_insertion_point(interface_extends:snakes.GameAnnouncement)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Текущие игроки
   * </pre>
   *
   * <code>required .snakes.GamePlayers players = 1;</code>
   * @return Whether the players field is set.
   */
  boolean hasPlayers();
  /**
   * <pre>
   * Текущие игроки
   * </pre>
   *
   * <code>required .snakes.GamePlayers players = 1;</code>
   * @return The players.
   */
  ru.ccfit.golubevm.snake.protobuf.protocol.GamePlayers getPlayers();
  /**
   * <pre>
   * Текущие игроки
   * </pre>
   *
   * <code>required .snakes.GamePlayers players = 1;</code>
   */
  ru.ccfit.golubevm.snake.protobuf.protocol.GamePlayersOrBuilder getPlayersOrBuilder();

  /**
   * <pre>
   * Параметры игры
   * </pre>
   *
   * <code>required .snakes.GameConfig config = 2;</code>
   * @return Whether the config field is set.
   */
  boolean hasConfig();
  /**
   * <pre>
   * Параметры игры
   * </pre>
   *
   * <code>required .snakes.GameConfig config = 2;</code>
   * @return The config.
   */
  ru.ccfit.golubevm.snake.protobuf.protocol.GameConfig getConfig();
  /**
   * <pre>
   * Параметры игры
   * </pre>
   *
   * <code>required .snakes.GameConfig config = 2;</code>
   */
  ru.ccfit.golubevm.snake.protobuf.protocol.GameConfigOrBuilder getConfigOrBuilder();

  /**
   * <pre>
   * Можно ли новому игроку присоединиться к игре (есть ли место на поле)
   * </pre>
   *
   * <code>optional bool can_join = 3 [default = true];</code>
   * @return Whether the canJoin field is set.
   */
  boolean hasCanJoin();
  /**
   * <pre>
   * Можно ли новому игроку присоединиться к игре (есть ли место на поле)
   * </pre>
   *
   * <code>optional bool can_join = 3 [default = true];</code>
   * @return The canJoin.
   */
  boolean getCanJoin();

  /**
   * <pre>
   * Глобально уникальное имя игры, например "my game"
   * </pre>
   *
   * <code>required string game_name = 4;</code>
   * @return Whether the gameName field is set.
   */
  boolean hasGameName();
  /**
   * <pre>
   * Глобально уникальное имя игры, например "my game"
   * </pre>
   *
   * <code>required string game_name = 4;</code>
   * @return The gameName.
   */
  java.lang.String getGameName();
  /**
   * <pre>
   * Глобально уникальное имя игры, например "my game"
   * </pre>
   *
   * <code>required string game_name = 4;</code>
   * @return The bytes for gameName.
   */
  com.google.protobuf.ByteString
      getGameNameBytes();
}
