// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

// Protobuf Java Version: 3.25.1
package ru.ccfit.golubevm.snake.protobuf.protocol;

public interface GamePlayersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:snakes.GamePlayers)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Список всех игроков
   * </pre>
   *
   * <code>repeated .snakes.GamePlayer players = 1;</code>
   */
  java.util.List<ru.ccfit.golubevm.snake.protobuf.protocol.GamePlayer> 
      getPlayersList();
  /**
   * <pre>
   * Список всех игроков
   * </pre>
   *
   * <code>repeated .snakes.GamePlayer players = 1;</code>
   */
  ru.ccfit.golubevm.snake.protobuf.protocol.GamePlayer getPlayers(int index);
  /**
   * <pre>
   * Список всех игроков
   * </pre>
   *
   * <code>repeated .snakes.GamePlayer players = 1;</code>
   */
  int getPlayersCount();
  /**
   * <pre>
   * Список всех игроков
   * </pre>
   *
   * <code>repeated .snakes.GamePlayer players = 1;</code>
   */
  java.util.List<? extends ru.ccfit.golubevm.snake.protobuf.protocol.GamePlayerOrBuilder> 
      getPlayersOrBuilderList();
  /**
   * <pre>
   * Список всех игроков
   * </pre>
   *
   * <code>repeated .snakes.GamePlayer players = 1;</code>
   */
  ru.ccfit.golubevm.snake.protobuf.protocol.GamePlayerOrBuilder getPlayersOrBuilder(
      int index);
}
